### ISSUE TITLE
Current firmware

### ISSUE THREAD

**Issue by kittikatt** [plutooo/freakyhax#3]
Not presently working on current firmware(Ver. 11.1.0-34), even with otherapp for the specified version. Just crashes and says the software encountered an error, restarting the system.

Will this be fixed?

**Comment by CodingKoopa** [comment]
Fixed as of [v2](https://github.com/plutooo/freakyhax/releases/tag/v2).

**Comment by plutooo** [comment]
Fixed now, hopefully.
