### ISSUE TITLE
Freakyhax doesn't work correctly

### ISSUE THREAD

**Issue by ludovicoludprio** [plutooo/freakyhax#6]
The homebrew launcher starts, but I can't open any app with the cartrige ( forexample the Alpha Sapphire randomizer or Save Manager ). When I try to open them the bottom screen become yellow and I have to take off the console. I have just tried to unistall and install freakyhax and homebrew, but the problem persists. Help!

**Comment by GalladeGuy** [comment]
Replace your boot.3dsx with this file and try again: [https://smealum.github.io/ninjhax2/boot.3dsx](url)

**Comment by ludovicoludprio** [comment]
It doesn't find the page. It says "404 This is not the web page you are looking for".

**Comment by TheNain38** [comment]
@ludovicoludprio
Here it should work:
https://smealum.github.io/ninjhax2/boot.3dsx
If you look at the link @GalladeGuy made, it incorrectly links to: "https://github.com/plutooo/freakyhax/issues/url" instead of: "https://smealum.github.io/ninjhax2/boot.3dsx"

**Comment by ludovicoludprio** [comment]
The problem persists

**Comment by plutooo** [comment]
This is not a problem with freakyhax, but with the homebrew launcher/homebrew environment.
